spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thesill
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: anhthang123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8000



